/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.15
 * Generated at: 2026-01-05 06:32:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class jlife_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


	 	// 선언 : 클래스 정의	jlife.jsp -> jlife_jsp.java
	 	// 최초 로드시 실행
	 	int aa = 1111;	// 멤버변수
	 	
	 	void meth_2() {
	 		System.out.println("meth_2() 실행: "+ ++aa);
	 		// out.print("out 출력");		선언부에서 내장객체 접근 불가능
	 	}
	 	
	 	public void jspInit() {
	 		System.out.println("jspInit() 실행");		// 최초 로드시 실행
	 	}
	 	public void jspDestroy() {
	 		System.out.println("jspDestroy() 실행");	// 소멸시 실행
	 	}
	 
  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>jsp lifecycle</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1>jsp lifecycle</h1>\r\n");
      out.write("	<!-- \r\n");
      out.write("		JSP script 요소\r\n");
      out.write("		1. 선언\r\n");
      out.write("		2. 스크립틀릿\r\n");
      out.write("		3. 표현식\r\n");
      out.write("		4. 주석\r\n");
      out.write("		\r\n");
      out.write("	 -->\r\n");
      out.write("	 \r\n");
      out.write("	 ");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");

		// 스크립틀릿 : _jspService()에 해당 --> 메소드, 메소드 안에서 메소드 정의 불가
		// 메소드 새로고침(요청) 이 있을 때마다 호출
		
		int a = 10;	// 지역변수
		String b = "아기상어";
		
		// 이너클래스
		class AAA {
			
		}
		
		System.out.println("스크립틀릿 실행 1");
		
		out.println("out 출력 1"+ ++a);	// out -> 클라이언트에 작성하는 stream 객체
		out.println("out 출력 2"+b);
		out.print("out 출력 3<br/>");
		out.print("out 출력 4<br/>");
		out.print("out 출력 5<br/>");
		
		System.out.println("스크립틀릿 실행 2");
		
		// 메소드 내에서 메소드 정의 불가
		// void meth() {}
		
		for (int i=0; i<5; i++) {
			out.print(i+"<br/>");
		}
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div>html 구간</div>\r\n");
      out.write("	<div>\r\n");
      out.write("		out.print(\"out 출력입니다. \"+a);\r\n");
      out.write("		<br/>\r\n");
      out.write("		a : ");
      out.print( a );
      out.write("\r\n");
      out.write("		<br/>\r\n");
      out.write("		b : ");
      out.print( b );
      out.write('	');
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- java 코드로 작성되지 않고 일반적인 문자열 -->\r\n");
      out.write("	\r\n");
      out.write("	");

		out.print("out 출력입니다. "+a);
		System.out.println("스크립틀릿 실행 3");
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<style>\r\n");
      out.write("		.box {\r\n");
      out.write("			width: 100px;\r\n");
      out.write("			height: 20px;\r\n");
      out.write("			border: 1px solid #333;\r\n");
      out.write("		}\r\n");
      out.write("	</style>\r\n");
      out.write("	");
 for(int i=10; i<50; i+=10) { 
      out.write("\r\n");
      out.write("		<div class=\"box\">box ");
      out.print( i );
      out.write("</div>\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");

		meth_2();	// 메소드 호출
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
