/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.15
 * Generated at: 2026-01-06 07:50:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.session;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.Enumeration;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.Enumeration");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>view</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1>view</h1>\r\n");

	// scope 내장객체 		- page, 		request, session, application
	// scope 속성 설정 가능 - pageContext, 	request, session, application
	
	/*
	 scope 내장객체 -    page,     request, session, application
	       속성설정 - pageContext, request, session, application
	
	
	
 영역			영역객체       	속성의 유효 범위
page    	pageContext    	해당 페이지가 클라이언트에 서비스를 제공하는 동안에만 유효합니다.
                          	(서블릿 인스턴스의 _jspService() 메소드가 실행되는 동안에만 유효합니다.)

request    	request			클라이언트 요청이 처리되는 동안 유효합니다.
		 					(forwarding, include를 이용하여 여러 페이지에 공유할 수 있습니다.

session		session			세션이 유지되는 동안 유효합니다.
							(하나의 브라우저에 1개의 세션이 생성되므로 같은 웹 브라우저 내에서 실행되는 페이지들이 속성을 공유할 수 있습니다.)

application	application		웹 어플리케이션이 실행되고 있는 동안에 유효합니다.
							(웹 컨테이너에서 해당 어플리케이션은 오직 하나만 실행되므로 4가지 영역 중 가장 큰 영역에 해당합니다.)
	
*/

      out.write("\r\n");
      out.write("	session과 application 정보만 확인 가능<br/><br/>\r\n");
      out.write("	(session)ss_id : ");
      out.print( session.getAttribute("ss_id") );
      out.write("<br/>\r\n");
      out.write("	(session)ss_age : ");
      out.print( session.getAttribute("ss_age") );
      out.write("<br/>\r\n");
      out.write("	(session)ss_arr : ");
      out.print( session.getAttribute("ss_arr") );
      out.write("<br/>\r\n");
      out.write("	<br/>\r\n");
      out.write("	\r\n");
      out.write("	(request)rr_id : ");
      out.print( request.getAttribute("rr_id") );
      out.write("<br/>\r\n");
      out.write("	(request)rr_age : ");
      out.print( request.getAttribute("rr_age") );
      out.write("<br/>\r\n");
      out.write("	<br/>\r\n");
      out.write("	\r\n");
      out.write("	(application)aa_id : ");
      out.print( application.getAttribute("aa_id") );
      out.write("<br/>\r\n");
      out.write("	(application)aa_age : ");
      out.print( application.getAttribute("aa_age") );
      out.write("<br/>\r\n");
      out.write("	<br/>\r\n");
      out.write("	(pageContext)pa_id : ");
      out.print( pageContext.getAttribute("pa_id") );
      out.write("<br/>\r\n");
      out.write("	(pageContext)pa_age : ");
      out.print( pageContext.getAttribute("pa_age") );
      out.write("<br/>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<hr/>\r\n");
      out.write("	getId : ");
      out.print( session.getId() );
      out.write("<br/>\r\n");
      out.write("	");

		// attribute 이름들을 가져옴
		Enumeration<String> attrNames = session.getAttributeNames();
	
		while(attrNames.hasMoreElements()) {
			String an = attrNames.nextElement();
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
      out.print( an );
      out.write(' ');
      out.write(':');
      out.write(' ');
      out.print( session.getAttribute(an) );
      out.write("<br/>\r\n");
      out.write("	");

		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
